#!/bin/bash

# Save the original working directory
orig_dir=$(pwd)

# Change the working directory to ./CSV_files/
cd ./CSV_files/

# Run the refresh-data.sh script
./scripts/refresh-data.sh

echo
echo "Converting .csv contents into INSERT statements in 'loaddata.sql'..."

# Create loaddata.sql in the parent directory
echo "-- Generated by script" > ../loaddata.sql

# Count total number of CSV files
total_files=$(ls *.csv | wc -l)

# Initialize counter for processed files
processed_files=0

# For each CSV file in the current directory
for file in *.csv
do
    # Get the table name from the file name
    table_name=$(basename "$file" .csv)

    # Read the CSV file into an array, excluding the header
    mapfile -t rows < <(tail -n +2 "$file")

    # For each row
    for row in "${rows[@]}"
    do
        # Convert the row to a SQL insert statement and append it to loaddata.sql
        echo "INSERT INTO $table_name VALUES ($(echo "$row" | sed "s/,/','/g" | sed "s/^/'/" | sed "s/$/'/"));" >> ../loaddata.sql
    done

    # Increment counter for processed files
    processed_files=$((processed_files + 1))

    # Calculate percentage of progress as a floating-point number and convert it to an integer
    percent=$(awk "BEGIN {printf \"%.0f\", 100 * $processed_files / $total_files}")

    # Print percentage of progress
    printf "\rProgress: %d%%" $percent
done

# Change back to the original working directory
cd "$orig_dir"

echo -e "\nGenerated 'loaddata.sql' successfully."