INSERT INTO Category VALUES ('CName');
INSERT INTO Category VALUES ('Electronics');
INSERT INTO Category VALUES ('Fashion');
INSERT INTO Category VALUES ('Home Appliances');
INSERT INTO Category VALUES ('Books');
INSERT INTO Category VALUES ('Sports');
INSERT INTO Category VALUES ('Groceries');
INSERT INTO Category VALUES ('Toys');
INSERT INTO Category VALUES ('Furniture');
INSERT INTO Category VALUES ('Automotive');
